"""initial_schema

Revision ID: 7b202b81edfb
Revises: 
Create Date: 2025-11-15 03:25:16.804208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b202b81edfb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_category"), "tags", ["category"], unique=False)
    op.create_index(op.f("ix_tags_slug"), "tags", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "blog_entries",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("excerpt", sa.String(), nullable=True),
        sa.Column("slug", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name="ck_blog_status"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_blog_entries_slug"), "blog_entries", ["slug"], unique=True)
    op.create_index(op.f("ix_blog_entries_user_id"), "blog_entries", ["user_id"], unique=False)
    op.create_table(
        "daily_reviews",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("review_date", sa.Date(), nullable=False),
        sa.Column("mood_rating", sa.Integer(), nullable=True),
        sa.Column("energy_level", sa.Integer(), nullable=True),
        sa.Column("productivity_rating", sa.Integer(), nullable=True),
        sa.Column("sleep_hours", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("sleep_quality", sa.Integer(), nullable=True),
        sa.Column("water_intake_ml", sa.Integer(), nullable=True),
        sa.Column("accomplishments", sa.String(), nullable=True),
        sa.Column("challenges", sa.String(), nullable=True),
        sa.Column("lessons_learned", sa.String(), nullable=True),
        sa.Column("gratitude", sa.String(), nullable=True),
        sa.Column("tomorrow_intentions", sa.String(), nullable=True),
        sa.Column("highlights", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "energy_level >= 1 AND energy_level <= 10", name="ck_review_energy_level"
        ),
        sa.CheckConstraint("mood_rating >= 1 AND mood_rating <= 10", name="ck_review_mood_rating"),
        sa.CheckConstraint(
            "productivity_rating >= 1 AND productivity_rating <= 10", name="ck_review_productivity"
        ),
        sa.CheckConstraint(
            "sleep_quality >= 1 AND sleep_quality <= 10", name="ck_review_sleep_quality"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "review_date", name="uq_user_review_date"),
    )
    op.create_index(op.f("ix_daily_reviews_user_id"), "daily_reviews", ["user_id"], unique=False)
    op.create_table(
        "foods",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("meal_date", sa.Date(), nullable=False),
        sa.Column("meal_time", sa.Time(), nullable=True),
        sa.Column("meal_type", sa.String(length=20), nullable=False),
        sa.Column("food_name", sa.String(length=255), nullable=False),
        sa.Column("portion_size", sa.String(length=100), nullable=True),
        sa.Column("calories", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("protein_grams", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("carbs_grams", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("fats_grams", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("fiber_grams", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("sugar_grams", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("sodium_mg", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')", name="ck_food_meal_type"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_foods_user_id"), "foods", ["user_id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("parent_goal_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("goal_type", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("target_value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("target_unit", sa.String(length=50), nullable=True),
        sa.Column("current_value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("is_recurring", sa.Boolean(), nullable=True),
        sa.Column("recurrence_pattern", sa.String(length=50), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "goal_type IN ('daily', 'weekly', 'monthly', 'yearly')", name="ck_goal_type"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'cancelled', 'paused')", name="ck_goal_status"
        ),
        sa.CheckConstraint("priority >= 0 AND priority <= 5", name="ck_goal_priority"),
        sa.ForeignKeyConstraint(
            ["parent_goal_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_goal_type"), "goals", ["goal_type"], unique=False)
    op.create_index(op.f("ix_goals_parent_goal_id"), "goals", ["parent_goal_id"], unique=False)
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "habits",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("target_days", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("reminder_time", sa.Time(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("current_streak", sa.Integer(), nullable=True),
        sa.Column("longest_streak", sa.Integer(), nullable=True),
        sa.Column("total_completions", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("frequency IN ('daily', 'weekly', 'custom')", name="ck_habit_frequency"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_habits_user_id"), "habits", ["user_id"], unique=False)
    op.create_table(
        "media",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("file_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column("related_to_type", sa.String(length=50), nullable=True),
        sa.Column("related_to_id", sa.UUID(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_file_type"), "media", ["file_type"], unique=False)
    op.create_index(op.f("ix_media_user_id"), "media", ["user_id"], unique=False)
    op.create_table(
        "progress_snapshots",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("snapshot_type", sa.String(length=50), nullable=False),
        sa.Column("total_goals", sa.Integer(), nullable=True),
        sa.Column("completed_goals", sa.Integer(), nullable=True),
        sa.Column("active_habits", sa.Integer(), nullable=True),
        sa.Column("habit_completion_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("total_workouts", sa.Integer(), nullable=True),
        sa.Column("total_workout_minutes", sa.Integer(), nullable=True),
        sa.Column("average_daily_mood", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("average_energy_level", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("total_blog_entries", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("weight_unit", sa.String(length=10), nullable=True),
        sa.Column("body_fat_percentage", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "snapshot_type IN ('weekly', 'monthly', 'yearly')", name="ck_snapshot_type"
        ),
        sa.CheckConstraint("weight_unit IN ('lbs', 'kg')", name="ck_snapshot_weight_unit"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "snapshot_date", "snapshot_type", name="uq_user_snapshot"),
    )
    op.create_index(
        op.f("ix_progress_snapshots_user_id"), "progress_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "taggables",
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("taggable_id", sa.UUID(), nullable=False),
        sa.Column("taggable_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "taggable_type IN ('goal', 'habit', 'blog_entry', 'workout', 'food', 'daily_review')",
            name="ck_taggable_type",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag_id", "taggable_type", "taggable_id", name="uq_tag_taggable"),
    )
    op.create_index(op.f("ix_taggables_tag_id"), "taggables", ["tag_id"], unique=False)
    op.create_table(
        "workouts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workout_date", sa.Date(), nullable=False),
        sa.Column("workout_time", sa.Time(), nullable=True),
        sa.Column("workout_type", sa.String(length=50), nullable=False),
        sa.Column("workout_name", sa.String(length=255), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("calories_burned", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("intensity", sa.String(length=20), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("mood_before", sa.String(length=20), nullable=True),
        sa.Column("mood_after", sa.String(length=20), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("intensity IN ('low', 'medium', 'high')", name="ck_workout_intensity"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workouts_user_id"), "workouts", ["user_id"], unique=False)
    op.create_table(
        "goal_progress",
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.Column("progress_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goal_progress_goal_id"), "goal_progress", ["goal_id"], unique=False)
    op.create_table(
        "habit_entries",
        sa.Column("habit_id", sa.UUID(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("mood", sa.String(length=20), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("habit_id", "entry_date", name="uq_habit_entry_date"),
    )
    op.create_index(op.f("ix_habit_entries_habit_id"), "habit_entries", ["habit_id"], unique=False)
    op.create_table(
        "workout_exercises",
        sa.Column("workout_id", sa.UUID(), nullable=False),
        sa.Column("exercise_name", sa.String(length=255), nullable=False),
        sa.Column("exercise_type", sa.String(length=50), nullable=True),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("weight_unit", sa.String(length=10), nullable=True),
        sa.Column("distance", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("distance_unit", sa.String(length=10), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "distance_unit IN ('miles', 'km', 'meters')", name="ck_exercise_distance_unit"
        ),
        sa.CheckConstraint("weight_unit IN ('lbs', 'kg')", name="ck_exercise_weight_unit"),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_exercises_workout_id"), "workout_exercises", ["workout_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_exercises_workout_id"), table_name="workout_exercises")
    op.drop_table("workout_exercises")
    op.drop_index(op.f("ix_habit_entries_habit_id"), table_name="habit_entries")
    op.drop_table("habit_entries")
    op.drop_index(op.f("ix_goal_progress_goal_id"), table_name="goal_progress")
    op.drop_table("goal_progress")
    op.drop_index(op.f("ix_workouts_user_id"), table_name="workouts")
    op.drop_table("workouts")
    op.drop_index(op.f("ix_taggables_tag_id"), table_name="taggables")
    op.drop_table("taggables")
    op.drop_index(op.f("ix_progress_snapshots_user_id"), table_name="progress_snapshots")
    op.drop_table("progress_snapshots")
    op.drop_index(op.f("ix_media_user_id"), table_name="media")
    op.drop_index(op.f("ix_media_file_type"), table_name="media")
    op.drop_table("media")
    op.drop_index(op.f("ix_habits_user_id"), table_name="habits")
    op.drop_table("habits")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_parent_goal_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_goal_type"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_foods_user_id"), table_name="foods")
    op.drop_table("foods")
    op.drop_index(op.f("ix_daily_reviews_user_id"), table_name="daily_reviews")
    op.drop_table("daily_reviews")
    op.drop_index(op.f("ix_blog_entries_user_id"), table_name="blog_entries")
    op.drop_index(op.f("ix_blog_entries_slug"), table_name="blog_entries")
    op.drop_table("blog_entries")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tags_slug"), table_name="tags")
    op.drop_index(op.f("ix_tags_category"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
